version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2
    steps:
      - checkout
      - run:
          name: test
          command: go test -v -cover -race -coverprofile cover.out ./...
      - run:
          name: cover
          command: go tool cover -html=cover.out -o cover.html
      - run:
          name: coveralls
          command: |
            go get github.com/mattn/goveralls
	          goveralls -coverprofile=cover.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - run:
          name: build
          command: go build