version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11.2
    steps:
      - checkout
      - run:
          name: install modules
          command: go mod download
      - run:
          name: build
          command: go build